spring.application.name=twin

# 1. Configuração da porta do servidor Spring Boot
server.port=8088

# 2. Configuração do URL do ESP32 (substitua pelo IP real do ESP32 na sua rede local)
# IMPORTANTE
esp32.url=http://10.74.241.175

